### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/ffpuppet#109]
```
[2021-09-07 19:56:17] Shutting down...
[2021-09-07 19:56:18] Done.
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\__main__.py", line 12, in <module>
    raise SystemExit(main(GrizzlyArgs().parse_args()))
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\main.py", line 137, in main
    session.run(
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\session.py", line 213, in run
    result = runner.run(
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\common\runner.py", line 213, in run
    server_status, served = self._server.serve_path(
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\sapphire\core.py", line 172, in serve_path
    was_timeout = not loadmgr.wait(self.timeout, continue_cb=continue_cb)
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\sapphire\connection_manager.py", line 89, in wait
    if continue_cb is not None and not continue_cb():
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\common\runner.py", line 294, in _keep_waiting
    return self._target.monitor.is_healthy()
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\grizzly\target\puppet_target.py", line 106, in is_healthy
    return self._puppet.is_healthy()
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\ffpuppet\core.py", line 646, in is_healthy
    if check.check():
  File "C:\Users\posidron\.virtualenvs\harness-pffzaeuq\lib\site-packages\ffpuppet\checks.py", line 86, in check
    data = "".join([log["buffer"], scan_fp.read(self.chunk_size)])
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4180: character maps to <undefined>
ERROR:root:Command '['C:\\Users\\posidron\\.virtualenvs\\harness-pffzaeuq\\Scripts\\python.exe', '-m', 'grizzly', '-v', '--log-level', 'INFO', '--platform', 'mypuppet', '--time-limit', '8', 'browser.exe', 'fuzzer']' returned non-zero exit status 1.
```

**Comment by tysmith** [comment]
Fixed by PR #111
